### ISSUE TITLE
Naming conventions in the RSS flows

### ISSUE THREAD

**Issue by vlderinger** [autoatml/autoplex#101]
The different parts of the RSS flows should be named systematically:

- Instead of "Sampling" I propose "select_structures" (if it's the step where we select from the full set of structures), as "sampling" could mean different things
- "Data_preprocessing" could be "process_data" (all other statements for similar jobs are in the imperative form)
- In fact can we name this in a more descriptive way (i.e. saying what data are processed, for example)? Something like "prepare_MLIP_fit"?

In general all naming needs to follow the conventions about lowercase / uppercase etc. (https://github.com/JaGeo/autoplex/blob/main/docs/dev/contributing.md#formatting-requirements - thanks @JaGeo!)

**Comment by QuantumChemist** [comment]
I would say that we can close this issue, can we? 👀
