### ISSUE TITLE
Custodian validators instead of handlers to avoid DFT errors

### ISSUE THREAD

**Issue by JaGeo** [autoatml/autoplex#141]
While removing the handlers of custodian to avoid automatic and inconsistent error handling is really important, we might want to replace some of them with validators (e.g., having a large sigma validator to check that the smearing is set okay)

**Comment by QuantumChemist** [comment]
@JaGeo , would you say that we still need to check custodian validators when we are planning to implement our own handlers?

**Comment by JaGeo** [comment]
I think we could take a look here as well.

**Comment by QuantumChemist** [comment]
@JaGeo , I'm not sure if I have to look somewhere else but here https://github.com/materialsproject/custodian/blob/master/src/custodian/vasp/validators.py I don't see a suitable validator for our purposes. I think we have to implement this on our own as well.

**Comment by JaGeo** [comment]
Then, we  close this issue
