### ISSUE TITLE
Incompatibility with torch version 2.4.1

### ISSUE THREAD

**Issue by YuanbinLiu** [autoatml/autoplex#142]
The current installation of autoplex automatically uses the latest torch version 2.4.1, which introduces significant changes that are incompatible with dgl. I recommend specifying torch version 2.2.1 during installation for now. I've also experienced incompatibility issues with newer YAML versions, so we could specify ruamel.yaml version 0.17.21 as well. Does anyone encounter a similar installation issue?

**Comment by naik-aakash** [comment]
Closing this as it is fixed already
