### ISSUE TITLE
 Robust (GAP) fitting parameters for the whole workflow as a default 

### ISSUE THREAD

**Issue by QuantumChemist** [autoatml/autoplex#149]
Hello!

The question of what GAP fitting parameters settings might be the best as the default in autoplex comes up from time to time and actually, I would need and like to have a bit more input from the Oxford-side here as my experience is mainly limited to Si for now.

That's why I would like to ask you @YuanbinLiu and @vlderinger , what you think might be the best choice for the crystalline phases here? Shall I take the Si GAP fit parameters as default or is there some other best practice that you could recommend?

**Comment by vlderinger** [comment]
It very much depends on your use case. The key things to think about with GAP are:

- What descriptors do you use to encode your structure? The Si model you refer to uses a SOAP descriptor together with a repulsive baseline model. Many published GAPs use a combination of 2b+SOAP or 2b+3b+SOAP terms ("hierarchical" descriptors, see Section 4.2 of https://doi.org/10.1021/acs.chemrev.1c00022).
- Once you've decided on descriptors, what hyperparameters do you use for them? The ones most important to think about are the cut-off radius for all interactions, and the smoothness used for SOAP. 
- And finally – the regularisation is very important (Section 4.6 of https://doi.org/10.1021/acs.chemrev.1c00022).

If you're going for "robust" parameters, I'd typically take that to mean a potential that can handle early stages of GAP-RSS: you want to include a 2-body term, and when in doubt start with a slightly smoother setting for SOAP (https://doi.org/10.1103/PhysRevLett.120.156001). 

For phonons, your requirements will be quite different: you need to focus on getting the forces in the displacement supercells very accurately, and perhaps use a custom regularisation for that (https://doi.org/10.1063/5.0013826), but the robustness is less critical as your atoms won't move very much!

Whether there's one type of generic settings, or separate ones for different workflows, is a very interesting question that we should discuss – either for GAP fitting specifically, or for all types of potentials we support (cc @YuanbinLiu @nfragapane @JaGeo).
