### ISSUE TITLE
set VASP makers to force_overwrite ?

### ISSUE THREAD

**Issue by QuantumChemist** [autoatml/autoplex#153]
Related to https://github.com/Matgenix/jobflow-remote/issues/197#issuecomment-2419950788

**Comment by QuantumChemist** [comment]
@JaGeo , do you think I shall set the VASP makers to force_overwrite if rerun jobs are now automatically overwritten in jobflow-remote?

**Comment by JaGeo** [comment]
I think we can simply close this issue. 😃
