### ISSUE TITLE
better storing of all the different xyz files

### ISSUE THREAD

**Issue by QuantumChemist** [autoatml/autoplex#160]
@naik-aakash pointed out that we might think about a better way to store and access the xyz files (train.xyz, train_wo_sigma.xyz, train_phonon.xyz etc.)

**Comment by naik-aakash** [comment]
Maybe storing the path to the extxyz as job/flow output could be an option where required.

**Comment by vlderinger** [comment]
On that topic – do we want to revisit the naming of the files at some point? (Not urgent!) For example, can we make the `wo_sigma` more self-explanatory? Or perhaps just write one `train.xyz` file, independent of which workflow uses it?

**Comment by QuantumChemist** [comment]
Hey @vlderinger ! Sure, we can think of how to rename the files, we could take `train_without_sigma.extxyz` if that filename is not too long for you? Only keeping one `train.extxyz` file in general when the sigma regularization is turned on would not be the best idea as I wanted to make the user be able to compare the fit with and without sigma regularization. We surely can make it default or optional to only have one `train.extxyz` file. Which option one would you prefer?

**Comment by vlderinger** [comment]
I'm not fully clear what you mean by "without sigma" - do you mean adding or removing atom-wise regularisation (Eq. 8 in https://doi.org/10.1063/5.0013826)? It's a rather specialised use-case, and you could determine these atom-wise terms "on the fly" from the forces, there's no need to store them in the .xyz file I think.

**Comment by vlderinger** [comment]
I'd generally keep names of files, routines, etc. as general as possible – at the moment the phonon workflow is one of the two main applications of autoplex, but I expect there will be more different ones in the future, and users may want to combine them in different ways. You could just have a flag somewhere that determines whether phonon data are to be added, and in that case have a routine within autoplex that applies custom regularisation for that class of input data (`config_type`)

**Comment by QuantumChemist** [comment]
@vlderinger , I'm referring to what happens when `set_sigma` https://github.com/autoatml/autoplex/blob/eda19f51822a20cfd679d2141c616614b41a68df/autoplex/fitting/common/regularization.py#L17 is called in the data-preprocessing step.

**Comment by vlderinger** [comment]
Ah! This looks like part of @MorrowChem 's routines? Different use-case, but similar story – you set regularisation based on some specific criterion. My comment above applies to both the phonon regularisation and the other routine. If no regularisation is set, GAP will default to the standard settings in the `gap_fit` input line – perhaps worth renaming `set_sigma` to `set_custom_sigma` to make this clear?

**Comment by QuantumChemist** [comment]
yes, this is a part that @MorrowChem contributed. 
I would say that I can make one `train.extxyz` file per default and make it optional that the user can also do another fit without the sigma regularization. In general, I wanted to restructure the code in a way that instead of having all kind of train files with different names in the same folder, I wanted to use several subfolders. This will require a few code changes though, that I could do next week before the RSS part is merged. What do you think @JaGeo ? I can also rename the function to `set_custom_sigma` 😄

**Comment by JaGeo** [comment]
I feel this is a minor issue that we could postpone a bit. Let's first get RSS updated

**Comment by QuantumChemist** [comment]
this is now changed (not reviewed yet) in https://github.com/autoatml/autoplex/pull/280
