### ISSUE TITLE
Clean up parameters of the class and in make

### ISSUE THREAD

**Issue by JaGeo** [autoatml/autoplex#165]
We might need to review once again which parameters should be defined while initialising the class and which while getting the job/flow via make. I feel there are still some inconsistencies.

It's not urgent but should be on our task lists.

- Rearrange and separate MLIP parameters in the CompleteDFTvsMLBenchmarkWorkflow. Move all general settings out of the make function and leave parameters that have to be adjusted for each system like e.g. GAP 2b, 3b, soap terms.

**Comment by QuantumChemist** [comment]
Could you give me a rule-of-thumb I could follow along?

**Comment by JaGeo** [comment]
In atomate2, we typically think about which of the properties might be system (structure) dependent (make part) and which are universal (class). 
I think the same applies here. Which parameters would need to change if you switch from Si to Sn, for example? Which can be universally defined.

**Comment by JaGeo** [comment]
As said: not critical for functionality at the moment but something to keep in mind.

**Comment by QuantumChemist** [comment]
> In atomate2, we typically think about which of the properties might be system (structure) dependent (make part) and which are universal (class). I think the same applies here. Which parameters would need to change if you switch from Si to Sn, for example? Which can be universally defined.

oh, that's a great tip! I know it's not critical, but I will start to apply it with new changes at least already. Thank you a lot!

**Comment by QuantumChemist** [comment]
- Rearrange and separate MLIP parameters in the CompleteDFTvsMLBenchmarkWorkflow. Move all general settings out of the make function and leave parameters that have to be adjusted for each system like e.g. GAP 2b, 3b soap terms.

**Comment by QuantumChemist** [comment]
this is now changed (not reviewed yet) in https://github.com/autoatml/autoplex/pull/280
