### ISSUE TITLE
Path to glue.xml is hardcoded

### ISSUE THREAD

**Issue by naik-aakash** [autoatml/autoplex#167]
I think, it would be best if it path to glue.xml is checked before hardcoding it. Currently even if custom path is provided, it is simply over written. Thus one cannot really use the user supplied path in gap fit function. 

https://github.com/autoatml/autoplex/blob/e5ea5e6cdb869ab46978c231703a79980c95ecc4/autoplex/fitting/common/utils.py#L173

I found this when I was adapting the test to not having to switch directories and simply provide path to the glue.xml file instead. Test will fail.

For now, i did not modify anything in source code and have simply restored the initial test implementation as before where we explicitly change working directory before executing the test just for this case. Adding it here, so we remember to update the source code soon.

**Comment by QuantumChemist** [comment]
The problem is actually hidden here https://github.com/autoatml/autoplex/blob/e5ea5e6cdb869ab46978c231703a79980c95ecc4/autoplex/fitting/common/utils.py#L1822 and I'm going to fix this today
