### ISSUE TITLE
M3GNet atomate2 interface

### ISSUE THREAD

**Issue by QuantumChemist** [autoatml/autoplex#181]
I adjusted the way the MLIP PhononMakers are called in autoplex to the new setup in atomate2. Now the test_auto_flows unit test for M3GNet has a unusual low RMSE (given the quality of the test data), so I think it is somehow switching to the pre-trained M3GNet potential. I need a bit more time to investigate why this happens.

**Comment by JaGeo** [comment]
Do the kwargs still work?

**Comment by JaGeo** [comment]
Likely to test for all of these forcefields (except for gap)

**Comment by QuantumChemist** [comment]
> Likely to test for all of these forcefields (except for gap)

For the other MLIPs the RMSE did not change, but I intended to check that anyway 😃

**Comment by QuantumChemist** [comment]
has been solved :)
