### ISSUE TITLE
Increase NELM and NSW default values for relaxmakers

### ISSUE THREAD

**Issue by QuantumChemist** [autoatml/autoplex#194]
Increase NELM and NSW default values for relaxmakers as (with custodian handlers turned off) jobs don't always converge.

**Comment by JaGeo** [comment]
We could only activate those handlers. This would also be a possibility

**Comment by QuantumChemist** [comment]
Hmmmm. I'd prefer to simply adjust the INCAR for now as we had a lot of other troubles with the custodian handler. Just seems that for Sb2Se3 we need some more ionic steps and I think it's good to then also increase the electronic steps too.

**Comment by JaGeo** [comment]
Yes, sure!

But maybe something for our todo. This is the list of default error handlers in atomate2: https://github.com/materialsproject/atomate2/blob/f11ac3709b69e8ce3fef9bfa22f16857e41f116e/src/atomate2/vasp/run.py#L39

**Comment by QuantumChemist** [comment]
The question is wheter the `NonConvergingErrorHandler` will also change ALGO? Because we don't want that, right?

**Comment by QuantumChemist** [comment]
shall I add it as an issue?
