### ISSUE TITLE
Check out `UnconvergedErrorHandler` or `NonConvergingErrorHandler` for relaxmakers

### ISSUE THREAD

**Issue by QuantumChemist** [autoatml/autoplex#195]
As discussed here: https://github.com/autoatml/autoplex/issues/194

**Comment by QuantumChemist** [comment]
Handlers: https://github.com/materialsproject/atomate2/blob/f11ac3709b69e8ce3fef9bfa22f16857e41f116e/src/atomate2/vasp/run.py#L39

**Comment by QuantumChemist** [comment]
Unfortunately, the `UnconvergedErrorHandler` changes the ALGO settings:
https://github.com/materialsproject/custodian/blob/55e9c10ac951553ad3766570b5868d9f1673fa1c/src/custodian/vasp/handlers.py#L1146

**Comment by QuantumChemist** [comment]
and `NonConvergingErrorHandler` changes it, too:
https://github.com/materialsproject/custodian/blob/55e9c10ac951553ad3766570b5868d9f1673fa1c/src/custodian/vasp/handlers.py#L1596

so I would close this issue for now

**Comment by JaGeo** [comment]
I think we need to write our own handlers and think about it very carefully.

**Comment by QuantumChemist** [comment]
yes, I agree. I will add it to the issues 😃
