### ISSUE TITLE
Dear developer, hello! I would very much like to ask if Autoplex has an active learning module?

### ISSUE THREAD

**Issue by stargolike** [autoatml/autoplex#196]
Dear developer, hello! I would very much like to ask if Autoplex has an active learning module?

**Comment by QuantumChemist** [comment]
Dear @stargolike , we don't have an active learning module yet.

**Comment by YuanbinLiu** [comment]
Hi @stargolike, thank you for your interest. We are indeed planning to integrate active learning modules into Autoplex. However, it still requires further development and testing. Please stay tuned for updates!

**Comment by stargolike** [comment]
> Hi @stargolike, thank you for your interest. We are indeed planning to integrate active learning modules into Autoplex. However, it still requires further development and testing. Please stay tuned for updates!

Thank you very much for your reply. I am very interested in this and will continue to focus on it.
