### ISSUE TITLE
Install trouble

### ISSUE THREAD

**Issue by stargolike** [autoatml/autoplex#197]
Dear developers, I'm currently in the process of installing autoplex. However, when I attempted to pip install autoplex following the instructions at [autoplex](https://autoatml.github.io/autoplex/user/index.html) and using the command `pip install autoplex`. some trouble happened.
```
ERROR: Could not find a version that satisfies the requirement autoplex (from versions: none)
ERROR: No matching distribution found for autoplex
```
Moreover, this trouble still persists after I have updated the pip source.
And I find this tutorial [jobflow](https://autoatml.github.io/autoplex/user/jobflowremote.html). When I run to the step of `pip install -e.[strict]`, other trouble happened.
```

  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Preparing editable metadata (pyproject.toml) ... done
Collecting atomate2@ git+https://github.com/materialsproject/atomate2.git@main (from atomate2[strict]@ git+https://github.com/materialsproject/atomate2.git@main->autoplex==0.2.9)
  Cloning https://github.com/materialsproject/atomate2.git (to revision main) to /tmp/pip-install-3b4mjhvi/atomate2_93a45298de274f53a65b5031ab377ccc
  Running command git clone --filter=blob:none --quiet https://github.com/materialsproject/atomate2.git /tmp/pip-install-3b4mjhvi/atomate2_93a45298de274f53a65b5031ab377ccc
  fatal: unable to access 'https://github.com/materialsproject/atomate2.git/': Failed to connect to github.com port 443 after 135488 ms: Connection timed out
  error: subprocess-exited-with-error
  
  × git clone --filter=blob:none --quiet https://github.com/materialsproject/atomate2.git /tmp/pip-install-3b4mjhvi/atomate2_93a45298de274f53a65b5031ab377ccc did not run successfully.
  │ exit code: 128
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× git clone --filter=blob:none --quiet https://github.com/materialsproject/atomate2.git /tmp/pip-install-3b4mjhvi/atomate2_93a45298de274f53a65b5031ab377ccc did not run successfully.
│ exit code: 128
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by JaGeo** [comment]
Thank you for your interest. Currently, we do not have autoplex on pypi. This will change in the next weeks. Please clone the repository first and then install it with `pip install .`. Thank you.

**Comment by stargolike** [comment]
> Thank you for your interest. Currently, we do not have autoplex on pypi. This will change in the next weeks. Please clone the repository first and then install it with `pip install .`. Thank you.

Thanks for your reply. I hope we can install it via PyPI next week. 😊

**Comment by QuantumChemist** [comment]
Dear @stargolike , you can also do `pip install git+https://github.com/autoatml/autoplex.git` without having to clone the repository.
