### ISSUE TITLE
Overwritten jobnames in phonon workflow when modified input sets are used

### ISSUE THREAD

**Issue by JaGeo** [autoatml/autoplex#198]
I would like to suggest renaming the jobs/workflows with new VASP settings within the workflow. In this way, the job names will stay consistent and not suffer from updated VASP settings and new names.

**Comment by QuantumChemist** [comment]
Could you give me one example of what you want the outcome to look like?

**Comment by QuantumChemist** [comment]
then I can add it to this PR https://github.com/autoatml/autoplex/pull/200 directly

**Comment by JaGeo** [comment]
I would like to have the same names for each job in the phonon workflow even when input makers might be overwritten (e.g., always `single displaced supercell static` or "rattled structures static" or "relax" etc. To avoid many updates, you could keep the names from the default workflow. I don't remember the exact names here.
