### ISSUE TITLE
Fix API reference section in docs

### ISSUE THREAD

**Issue by naik-aakash** [autoatml/autoplex#204]
There are quite some places in the codebase where a non-standard way of doc-strings is used, causing issues in rendering the doc-strings automatically correctly, and this needs to be fixed.

Eg: 
https://github.com/autoatml/autoplex/blob/eda19f51822a20cfd679d2141c616614b41a68df/autoplex/data/rss/utils.py#L96

**Comment by JaGeo** [comment]
I might have overlooked this while merging. Thanks for finding this.
