### ISSUE TITLE
Setup auto ghcr.io registry cleanup

### ISSUE THREAD

**Issue by naik-aakash** [autoatml/autoplex#205]
Currently lot of untagged docker images get pilled up when a new docker build workflow is run.

https://github.com/autoatml/autoplex/pkgs/container/autoplex%2Fautoplex/versions?filters%5Bversion_type%5D=untagged

Would be nice to have this automatically cleaned up

**Comment by naik-aakash** [comment]
Could be setup via this actions https://github.com/marketplace/actions/ghcr-io-cleanup-action

**Comment by QuantumChemist** [comment]
is there a way to also manually clean it up?

**Comment by naik-aakash** [comment]
Some issues with workflow need to be sorted
