### ISSUE TITLE
BUG: Bechmark summaries when switching from GAP to MACE in phonon workflow

### ISSUE THREAD

**Issue by JaGeo** [autoatml/autoplex#216]
When I switch from GAP to MACE, the benchmark summaries are not updated accordingly. It is not clear that MACE has been used. Instead, sometimes GAP default values are inserted.

**Comment by QuantumChemist** [comment]
I'm working on fixing this now. 
Does it at least show the correct potential name for you?
E.g. this is my outcome from the unit test:
<img width="626" alt="image" src="https://github.com/user-attachments/assets/0a1fded0-c66d-4221-8808-a9d10c7d1c41">
