### ISSUE TITLE
some suggestions

### ISSUE THREAD

**Issue by stargolike** [autoatml/autoplex#236]
Dear developers, I'd like to put forward some suggestions.

First, it's about the Python version. I had been using Python 3.9 for a long time and didn't encounter any errors during the installation of atomate2. So, I proceeded with the installation. However, autoplex can only be installed successfully with Python 3.10. Before creating a virtual environment using Conda, the documentation should prompt the use of Python 3.10 or a higher version.

Second, due to my personal network issues, it's quite difficult for me to connect to the Materials Project. But autoplex doesn't provide any examples that can run without MPRest. The basic and main functions like `CompleteDFTvsMLBenchmarkWorkflow `and `DFTSupercellSettingsMaker` can only be run with `mpids`. Could you please open up the interface to allow the import of locally stored structures using `pymatgen` or `ase`?

**Comment by JaGeo** [comment]
Dear @stargolike , 

we are still actively developing this package. Not all of the documentation is already in place. Just yesterday, we released the first stable version to Pypi. We have not yet done a wide announcement of this package.

To your first question: please check out the README.md of this package. It now clearly indicates that only Python 3.10 can be used. This actually comes from the fact that both atomate2 and pymatgen have dropped support.

To your second question: You can surely load in other structure files easily. "mpids" within the workflow can be any string representation of a specific structure. They just have to be unique. 

We expect that the package will be sufficiently documented for people familiar with Python, pymatgen and atomate2 within the next two weeks. Thank you for your understanding.

**Comment by JaGeo** [comment]
@QuantumChemist Based on this question, we could maybe indicate that the "mpid" in our workflow can be any string representation that is unique for a specific structure.

**Comment by QuantumChemist** [comment]
> @QuantumChemist Based on this question, we could maybe indicate that the "mpid" in our workflow can be any string representation that is unique for a specific structure.

Dear @stargolike,

it is true that autoplex relies on the mpids as structure identifier, but you can use any type of string, e.g. here in the unit test, I just put "test" https://github.com/autoatml/autoplex/blob/b6f080fcab9b32abf54cd1b8721e3045b9fcaf28/tests/auto/test_auto_flows.py#L507 
Therefore the crucial input element is the structure and for the structure you can use e.g. your POSCAR file like the following:
```
path_to_struct = "/path/to/POSCAR"
structure = Structure.from_file(path_to_struct)
```
Then you can pass this structure in a list to the workflow. I hope this helps!

**Comment by QuantumChemist** [comment]
Dear @stargolike , also please note that pymatgen and atomate2 have dropped their python 3.9 support as well, see here https://github.com/materialsproject/pymatgen/pull/4009 e.g.

**Comment by stargolike** [comment]
> Dear @stargolike , also please note that pymatgen and atomate2 have dropped their python 3.9 support a while ago as well, see here [materialsproject/pymatgen#4009](https://github.com/materialsproject/pymatgen/pull/4009) e.g.



> @QuantumChemist Based on this question, we could maybe indicate that the "mpid" in our workflow can be any string representation that is unique for a specific structure.

Thank you very much for your reply. I'm extremely sorry for not noticing the Python version. I will try to run AutoPlex in that way.

**Comment by JaGeo** [comment]
@stargolike don't worry! We are happy that people have interest in our code! 😃
