### ISSUE TITLE
Unit Tests need to be refactored to match src code structure

### ISSUE THREAD

**Issue by naik-aakash** [autoatml/autoplex#281]
Currently, the tests do not match the src code module structure. Submodule tests have seemed to got mixed up

Ideally,  should be separated for each module for easier tracking

The structure should be something on the lines

For example for` autoplex.auto`
```python
tests/auto/phonons/test_jobs.py
tests/auto/phonons/test_flows.py
tests/auto/rss/test_jobs.py
tests/auto/rss/test_flows.py
...
```

**Comment by QuantumChemist** [comment]
this is now changed (not reviewed yet) in https://github.com/autoatml/autoplex/pull/280
